---
title: "Buzz Loot History"
author: "Kevin Magnan"
output:
  html_document: default
---
<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup and libraries, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(
  jsonlite,
  data.table,
  DT,
  tidyverse,
  lubridate,
  tidyr,
  janitor,
  purrr,
  sunburstR,
  d3r,
  plotly,
  readr,
  shiny
)
```

```{r Load Data, echo=FALSE, warning=FALSE, message=FALSE}
## load json file
buzz_raw <- data.table(fromJSON("~/GitHub/kjmagnan1s.github.io/Buzz_ThatsMyBiS/buzz_character-json.json", flatten = TRUE))

## load iter/patterns from P6
tier6_itemID <- read_csv("phase6_itemIDs.csv")

## load tmb loot details
loot_slot_details <- read.csv("loot_details_slot.csv")

## create master table of raiders
buzz_master <- data.table(fromJSON("~/GitHub/kjmagnan1s.github.io/Buzz_ThatsMyBiS/buzz_character-json.json")) %>% 
  select(1, 2, 3, 4, 7, 8, 9, 10, 11)
  # limit colunmns to a master table of buzz character names  

# klsjhjfdkl
test_invtype <- buzz_raw %>% unnest(received, names_repair = "unique") %>% data.table("name...43", "inventory_type")

## unpack dataframes within raw json and limit columns
buzz_received <- buzz_raw %>%  
  unnest(received, names_repair = "unique") %>% 
    # unnest wishlist column into its own table and make all column names unique
  select(1,4,38,39,43,60,63) %>% 
  # limit columns
  rename(uuid = id...38,id = id...1, char_name = name...4, item_name = name...43, offspec_yn = pivot.is_offspec, date_received = pivot.received_at) %>% 
  # rename columns
  mutate(wowhead_link = paste0("<a href=",'"https://tbc.wowhead.com/item=',item_id,'">Link</a>'))
  # insert item_id into a wowhead link

## join received and wishlisted items to master list
buzz_master_received <- left_join(buzz_master, buzz_received, by = "id") %>%
  # join received table with master character table
  unite('spec', spec:spec_label, sep = ' | ', remove = FALSE) %>%
  #combine spec and spec label
  select(uuid, name, class, archetype, spec, item_id, item_name, offspec_yn, wowhead_link, date_received) %>%
  #limit columns
  mutate(date_received = ymd_hms(date_received)) %>% 
  separate(date_received, into = c("date_received"), sep = " ") %>% 
  # format date received column for proper filtering in table and remove time
  mutate(Phase = case_when(
    date_received <= "2022-01-26 00:00:'00" ~ "Phase 2",
    date_received >= "2022-01-30 00:00:00" ~ "Phase 3")) %>% 
  # logical for grouping loot into TBC phased releases 
  mutate(offspec_yn = ifelse(offspec_yn == 1, "Y", "N")) %>%
  # recode received column to Y/N
  left_join((loot_slot_details %>% select(item_name, Slot)), by = (c("item_name" = "item_name"))) %>% 
  # join in item slot
  rename(Name = name, Class = class, Role = archetype, Spec = spec, 'Item ID' = item_id, 'Item Name' = item_name, 'Item Slot' = Slot,'Offspec (Y/N)' = offspec_yn, ` ` = wowhead_link, 'Date Received' = date_received)
  # final rename
```

## ThatsMyBiS Loot Received

```{r Received Table, echo=FALSE, warning=FALSE, message=FALSE}

## Analytics:

## GitHub style calendar heat map of loot

## RShiny(?) dashboard or analytics looking at class/spec loot distrubution. Would be nice to include toggle buttons for MS>OS
## A box and whisker interactive viz for loot for each class with different specs colored/symbols is a good one

buzz_received_table <- buzz_master_received %>% select(Name, Class, Role, Spec, `Item Name`, `Item Slot`, `Offspec (Y/N)`, ` `, `Date Received`, Phase)
#remove unnecesary columns

datatable(buzz_received_table %>% 
            mutate(across(c(Name, Class, Role, Spec, `Item Slot`, `Offspec (Y/N)`, Phase), factor)) %>% 
            distinct()
            # factor columns for better filtering in table
            , class = 'display cell-border stripe hover row-border', filter = 'top', extensions = c('ColReorder', 'Scroller', 'Select', 'SearchPanes'), rownames = FALSE, selection = 'none', escape = FALSE,
            options = list(pageLength = 40, 
                         #order = list(8, 'desc'), 
                         colReorder = TRUE, deferRender = TRUE, scrollY = 500, scroller = TRUE, order = 
                           list(list(8, 'desc')),
                         searchCols = list(
                           NULL, NULL, NULL, NULL, NULL, NULL, list(search = '["N"]'), NULL, NULL, list(search = '["Phase 3"]'))),
            caption = "Export of Giant JSON blob on ThatsMyBiS. All BUZZ guilds characters and loot received.")

```

## ThatsMyBiS Active Wishlist

```{r Wishlist Table, echo=FALSE, warning=FALSE, message=FALSE}
buzz_wishlist <- buzz_raw %>%  
  unnest(wishlist, names_repair = "unique") %>%
  # unnest wishlist column into its own table and make all column names unique
  select(1,4,42,44,46,52,62,65,71,67) %>% 
  # limit columns selected
  rename(id = id...1, char_name = name...4, item_name = name...46, 'Item Order' = pivot.order, received_yn = pivot.is_received, last_updated = pivot.updated_at) %>% 
  # rename columns
  mutate(wowhead_link = paste0("<a href=",'"https://tbc.wowhead.com/item=',item_id,'">Link</a>'))
  # insert item_ids into a wowhead link

buzz_master_wishlist <- left_join(buzz_master, buzz_wishlist, by = "id") %>%
  # join the wishlist table to the master character table
  unite('spec', spec:spec_label, sep = ' | ', remove = FALSE) %>%
  # combine spec and spec label
  select(name, class, archetype, spec, item_id, parent_item_id, item_name, instance_name, 'Item Order', received_yn, wowhead_link, last_updated, pivot.note) %>%
  #limit columns
  left_join((loot_slot_details %>% select(item_name, Slot)), by = (c("item_name" = "item_name"))) %>%
  # join item slot name
  mutate(across(c(name, class, archetype, spec, instance_name, received_yn, Slot), factor)) %>%
  # factor columns for better filtering in table
  mutate(received_yn = ifelse(received_yn == 1, "Y", "N")) %>%
  # recode received column to Y/N
  mutate(last_updated = ymd_hms(last_updated)) %>%
  separate(last_updated, into = c("last_updated"), sep = " ") %>% 
  # format datetime column properly and remove time
  rename(Name = name, Class = class, Role = archetype, Spec = spec, item_ID = item_id, 'Item Name' = item_name, 'Instance Name' = instance_name, 'Received (Y/N)' = received_yn, ` ` = wowhead_link, 'Last Updated' = last_updated, 'Note' = pivot.note, `Item Slot` = Slot)
  # rename columns

buzz_wishlist_table <- buzz_master_wishlist %>%  select(!c(`Item Order`))
#remove column(s) for wishlist table

datatable(buzz_wishlist_table %>% 
            select(Name, Class, Role, Spec, `Item Name`, `Item Slot`, `Instance Name`, `Received (Y/N)`, ` `,`Last Updated`, Note) %>% 
            # remove unnecessary columns for better table viewing
            distinct()
          , class = 'display cell-border stripe hover row-border', filter = 'top', extensions = c('ColReorder', 'Scroller', 'Buttons'), escape = FALSE, rownames = FALSE,
          options = list(pageLength = 25,colReorder = TRUE, deferRender = TRUE, scrollY = 500, scroller = TRUE, dom = 'Blfrtip', order = 
                           list(list(9, 'desc')),
                        buttons = c('copy', 'csv', 'excel')),
          caption = "Export of Giant JSON blob on ThatsMyBiS. All BUZZ guilds characters with their wish lists for Phase 3.")
```

## Buzz wishlists aggregated 
```{r Wishlist Count Table, echo=FALSE, warning=FALSE, message=FALSE}
## add epic pattern drops later and join in

wishlist_aggregated <- buzz_wishlist_table %>%
            select(!c(`Item Slot`)) %>% 
            filter(`Received (Y/N)` == "N") %>% 
            left_join(tier6_itemID, by = c("parent_item_id" = "item_ID")) %>% 
            # join tier6 google doc with data fixes from WoWHead for tier and patterns
            mutate(across(c(`Item Name`, `Instance Name`), as.character)) %>% 
            # un-factor these columns, re-factor later
            mutate(across(c(item_ID), as.double)) %>%                         
            # convert to double to be compared against another double column
            mutate(`Item Name` = case_when(                                   
              `Instance Name` %in% NA  ~ Token_Pattern,
              TRUE ~ `Item Name`)) %>%
            # logical statement to replace item name with tier/pattern name when instance is NA
            mutate(`Instance Name` = case_when(                               # logical statement to replace zone when NA
              `Instance Name` %in% NA ~ Zone,
              TRUE ~ `Instance Name`)) %>%
            # logical statement to replace zone when NA
            mutate(item_ID = case_when(                                       
              item_ID < parent_item_id ~ parent_item_id,
              TRUE ~ item_ID)) %>%
            # logical statement to replace item_ID with parent_ID when applicable for wowhead link
            left_join((loot_slot_details %>% select(item_name, `Item Slot` = Slot)), by = (c("Item Name" = "item_name"))) %>%
            # join item slot name
            distinct() %>% 
            # remove any dupes
            mutate(across(c(`Instance Name`), factor)) %>%
            # restore factor for filtering
            mutate(` `= paste0("<a href=",'"https://tbc.wowhead.com/item=',item_ID,'">Link</a>')) %>% 
            # replace wowhead links with token/pattern item_ids when applicable
            drop_na(`Item Name`) %>% 
            select(!c(item_ID, parent_item_id, Zone, Token_Pattern))
            # deselect columns


datatable(wishlist_aggregated %>% 
            select(`Item Name`, Name, `Instance Name`, ` `, Class, Role) %>% 
            # limit columns
            group_by(`Item Name`, Name) %>%
            # group by columns to aggregate on
            summarise(Count = n()) %>% 
            # count rows
            summarise(Wishlisted = str_c(Name, collapse = ", "), Count = sum(Count)) %>%
            # collapse character names into a single string and sum up counts
            filter(Count >= 2) %>% 
            # retain wishlisted items over 2
            left_join((wishlist_aggregated %>% select(`Item Name`, `Item Slot`,`Instance Name`, ` `) %>% group_by(`Item Name`)), by = "Item Name") %>% 
            # reintroduce item data and wowhead link, remove duplicate rows
            mutate(across(c(`Item Slot`),factor)) %>% 
            #factor item slot
            select(`Item Name`, `Item Slot`, Wishlisted, Count, `Instance Name`, ` `, ) %>% 
            # reduce columns
            distinct()
            # remove dupes
            , class = 'display cell-border stripe hover row-border', filter = 'top', extensions = c('ColReorder', 'Scroller', 'Buttons'), 
          escape = FALSE, rownames = FALSE, options = list(pageLength = 25, colReorder = TRUE, deferRender = TRUE, scrollY = 500, scroller = TRUE, dom = 'Blfrtip', order = 
                                                             list(list(3, 'desc')),
                        buttons = c('copy', 'csv', 'excel')),
          caption = "Showing items on 2+ wishlists only; rep items removed from aggregation.")
```
Data as of `r file.info("~/GitHub/kjmagnan1s.github.io/Buzz_ThatsMyBiS/buzz_character-json.json")$mtime`

R Code updated `r Sys.Date()`

<hr/>


## Fun stuff

```{r GitHub Calendar, echo=FALSE, warning=FALSE, message=FALSE, fig.width=15, fig.height=6}

## Fun idea to recreate the GitHub calendar heatmap. Doesn't work very well since loot gets recorded in a lag.
## Instead of by month, factor the data by slot number - head, shoulder, hands, boots, legs, etc

# by_day <- buzz_master_received %>% 
#   mutate(
#     `Date Received` = as_datetime(`Date Received`, ),
#     created_date = floor_date(`Date Received`, "day"),
#     week_day = wday(`Date Received`)
#   ) %>% 
#   select(`Date Received`, week_day) %>% 
#   na.omit() %>% 
#   mutate(
#     week_day = factor(week_day, levels = 1:7, labels = c(
#       "Sun", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat"
#     )),
#     week = floor_date(`Date Received`, "week"),
#     week = as_date(week),
#     month = floor_date(`Date Received`, "month"),
#     month = as_date(month)
#   ) %>% 
#   group_by(week, week_day, month) %>% 
#   count(name = "count")
# 
# months <- seq(min(by_day$month), max(by_day$month), by = "month")
# months_label <- strftime(months, "%b")
# 
# less <- grid::textGrob("Less", gp = grid::gpar(fontsize = 10, col = "#767676"))
# more <- grid::textGrob("More", gp = grid::gpar(fontsize = 10, col = "#767676"))
# 
# by_day %>% ggplot() +
#       aes(week, fct_rev(week_day), fill = count) +
#       geom_tile(width = 0.90 * 7, height = 0.90) +
#       coord_fixed(7) +
#       theme_minimal(18, base_family = "PT Sans") +
#       labs(x = NULL, y = NULL) +
#       scale_x_date(expand = c(0, 0), breaks = months, labels = months_label) +
#       ggsci::scale_fill_material("deep-orange") +
#       theme(
#         legend.position = "bottom",
#         panel.grid = element_blank(),
#         axis.ticks.y = element_blank(),
#         axis.text.x = element_text(hjust = 0.5),
#         plot.margin = margin(1.5, 0, 1.5, 0)
#       )

# arrange columns into factors and count number of items per class per slot
by_slot <- buzz_master_received %>% 
   mutate(across(c(Class, `Item Slot`), factor)) %>% 
  na.omit() %>%
  filter(!(`Item Slot` == "N/A") & `Offspec (Y/N)` == "N") %>% 
  group_by(Class, `Item Slot`) %>% 
  count(name = "count") %>% 
  mutate(fill = cut(count,
                    seq(0, 12, 2),
                    right = TRUE,
                    labels = c("2", "4", "6", "8", "10", "12")
                    ))
                    
Class_label <- by_slot$Class
Item_slot_label <- by_slot$`Item Slot`

less <- grid::textGrob("Less", gp = grid::gpar(fontsize = 10, col = "767676"))
more <- grid::textGrob("More", gp = grid::gpar(fontsize = 10, col = "767676"))

# ggplotly(
by_slot %>% ggplot() +
  aes(`Item Slot`, Class, fill = fill) +
  geom_tile(
    width = .8, height = .8
  ) +
  coord_fixed(ratio = 1) +
  geom_hline(yintercept = seq(.5, 9, 1), col = "white", size = 2) +
  geom_vline(xintercept = seq(.5, 15, 1), col = "white", size = 2) +
  theme_minimal(12, base_family = "PT Sans") +
  labs(x = NULL, y = NULL) +
  scale_x_discrete(expand = c(0,0), breaks = by_slot$`Item Slot`, labels = Item_slot_label) +
  scale_fill_manual(
    limits = levels(fill),
    values = c("#EBEDF0", "#C6E48B", "#7BC96F", "#239A3B", "#196127", "#154F21"),
    name = NULL
  ) +
#  scale_fill_gradientn(colors = jdb_palette("brewer_green"), na.value = "grey") +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.grid = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    plot.margin = margin(1.5, 0, 1.5, 0),
    plot.title = element_text(hjust = 0.05, vjust = 0, size = 12, family = "PT Sans")
  ) +
 ggtitle(paste0(nrow(buzz_master_received %>% filter(!(`Item Slot` == "N/A") & `Offspec (Y/N)` == "N")) - 1, " pieces of loot awarded so far")) +
  guides(fill = guide_legend(nrow = 1)) +
   annotation_custom(less,
                     xmin = 2,
                     xmax = 2, ymin = -4, ymax = -2) +
   annotation_custom(more,
                     xmin = 12,
                     xmax = 12, ymin = -4, ymax = -2)
# ) 

# # this is necessary to get the annotations outside the plotting area to print
# gt <- ggplot_gtable(ggplot_build(cal))
# gt$layout$clip[gt$layout$name == "panel"] <- "off"
# grid::grid.draw(gt)
```

```{r sunburst, echo=FALSE, warning=FALSE, message=FALSE}
by_class_spec <- buzz_master_received %>% filter(`Offspec (Y/N)` == "N") %>%
 separate(Spec, into = c("Spec")) %>% 
 group_by(Class, Role, Spec) %>%
 count(name = "count") %>%
 mutate(count = as.double(count)) %>% 
 mutate(sequence = paste0(Class, "-",Role, "-", Spec)) %>% 
 ungroup() %>% 
 select(sequence, count)

by_class_spec <- data.frame(by_class_spec, stringsAsFactors = FALSE)

sb1 <- sunburst(by_class_spec, width = "50%", height = 400, count = TRUE)
sb1

sb2 <- sund2b(by_class_spec,
              colors = list(range = RColorBrewer::brewer.pal(9, "Greens")),
              rootLabel = list('Loot'),
              width = "100%",
              height = 400)
sb2
```
``` {r Next step ideas, echo=FALSE, warning=FALSE, message=FALSE}
## Next steps

# item weights from pre-TMB list and current updated list

# add summary table by class, spec, character? 

# figure out selection panel -- 

# datatable(
#   iris,
#   options = list(dom = 'Pfrtip', columnDefs = list(list(
#     searchPanes = list(show = FALSE), targets = 1:4
#   ))),
#   extensions = c('Select', 'SearchPanes'),
#   selection = 'none'
# )

## Create a Item wishlist table with players who wishlisted. Swap the group_by from Player > item to Item > player > priority.
```
